// Code generated by Wire protocol buffer compiler, do not edit.
// Source: strims.network.v1.bootstrap.BootstrapPeerListNetworksRequest in network/v1/bootstrap/peer.proto
package gg.strims.api.network.v1.bootstrap

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.jvm.JvmField
import okio.ByteString

class BootstrapPeerListNetworksRequest(
  unknownFields: ByteString = ByteString.EMPTY
) : Message<BootstrapPeerListNetworksRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BootstrapPeerListNetworksRequest) return false
    if (unknownFields != other.unknownFields) return false
    return true
  }

  override fun hashCode(): Int = unknownFields.hashCode()

  override fun toString(): String = "BootstrapPeerListNetworksRequest{}"

  fun copy(unknownFields: ByteString = this.unknownFields): BootstrapPeerListNetworksRequest =
      BootstrapPeerListNetworksRequest(unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<BootstrapPeerListNetworksRequest> = object :
        ProtoAdapter<BootstrapPeerListNetworksRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      BootstrapPeerListNetworksRequest::class, 
      "type.googleapis.com/strims.network.v1.bootstrap.BootstrapPeerListNetworksRequest", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: BootstrapPeerListNetworksRequest): Int {
        var size = value.unknownFields.size
        return size
      }

      override fun encode(writer: ProtoWriter, value: BootstrapPeerListNetworksRequest) {
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): BootstrapPeerListNetworksRequest {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return BootstrapPeerListNetworksRequest(
          unknownFields = unknownFields
        )
      }

      override fun redact(value: BootstrapPeerListNetworksRequest): BootstrapPeerListNetworksRequest
          = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
