// Code generated by Wire protocol buffer compiler, do not edit.
// Source: strims.dao.v1.SecondaryIndexKey in dao/v1/dao.proto
package gg.strims.dao.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class SecondaryIndexKey(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY
  )
  val key: ByteString = ByteString.EMPTY,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY
  )
  val id: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<SecondaryIndexKey, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SecondaryIndexKey) return false
    if (unknownFields != other.unknownFields) return false
    if (key != other.key) return false
    if (id != other.id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + key.hashCode()
      result = result * 37 + id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """key=$key"""
    result += """id=$id"""
    return result.joinToString(prefix = "SecondaryIndexKey{", separator = ", ", postfix = "}")
  }

  fun copy(
    key: ByteString = this.key,
    id: Long = this.id,
    unknownFields: ByteString = this.unknownFields
  ): SecondaryIndexKey = SecondaryIndexKey(key, id, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<SecondaryIndexKey> = object : ProtoAdapter<SecondaryIndexKey>(
      FieldEncoding.LENGTH_DELIMITED, 
      SecondaryIndexKey::class, 
      "type.googleapis.com/strims.dao.v1.SecondaryIndexKey", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: SecondaryIndexKey): Int {
        var size = value.unknownFields.size
        if (value.key != ByteString.EMPTY) size += ProtoAdapter.BYTES.encodedSizeWithTag(1,
            value.key)
        if (value.id != 0L) size += ProtoAdapter.UINT64.encodedSizeWithTag(2, value.id)
        return size
      }

      override fun encode(writer: ProtoWriter, value: SecondaryIndexKey) {
        if (value.key != ByteString.EMPTY) ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.key)
        if (value.id != 0L) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.id)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): SecondaryIndexKey {
        var key: ByteString = ByteString.EMPTY
        var id: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> key = ProtoAdapter.BYTES.decode(reader)
            2 -> id = ProtoAdapter.UINT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SecondaryIndexKey(
          key = key,
          id = id,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: SecondaryIndexKey): SecondaryIndexKey = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
