// Code generated by Wire protocol buffer compiler, do not edit.
// Source: DirectoryFrontendOpenResponse in directory.proto
package gg.strims.ppspp.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class DirectoryFrontendOpenResponse(
  @field:WireField(
    tag = 1,
    adapter = "gg.strims.ppspp.proto.DirectoryEvent#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val event: DirectoryEvent? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<DirectoryFrontendOpenResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DirectoryFrontendOpenResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (event != other.event) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + event.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (event != null) result += """event=$event"""
    return result.joinToString(prefix = "DirectoryFrontendOpenResponse{", separator = ", ", postfix
        = "}")
  }

  fun copy(event: DirectoryEvent? = this.event, unknownFields: ByteString = this.unknownFields):
      DirectoryFrontendOpenResponse = DirectoryFrontendOpenResponse(event, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<DirectoryFrontendOpenResponse> = object :
        ProtoAdapter<DirectoryFrontendOpenResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      DirectoryFrontendOpenResponse::class, 
      "type.googleapis.com/DirectoryFrontendOpenResponse", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: DirectoryFrontendOpenResponse): Int {
        var size = value.unknownFields.size
        if (value.event != null) size += DirectoryEvent.ADAPTER.encodedSizeWithTag(1, value.event)
        return size
      }

      override fun encode(writer: ProtoWriter, value: DirectoryFrontendOpenResponse) {
        if (value.event != null) DirectoryEvent.ADAPTER.encodeWithTag(writer, 1, value.event)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): DirectoryFrontendOpenResponse {
        var event: DirectoryEvent? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> event = DirectoryEvent.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DirectoryFrontendOpenResponse(
          event = event,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: DirectoryFrontendOpenResponse): DirectoryFrontendOpenResponse =
          value.copy(
        event = value.event?.let(DirectoryEvent.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
