// Code generated by Wire protocol buffer compiler, do not edit.
// Source: ListBootstrapClientsResponse in vpn.proto
package gg.strims.ppspp.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

class ListBootstrapClientsResponse(
  bootstrap_clients: List<BootstrapClient> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ListBootstrapClientsResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "gg.strims.ppspp.proto.BootstrapClient#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "bootstrapClients"
  )
  val bootstrap_clients: List<BootstrapClient> = immutableCopyOf("bootstrap_clients",
      bootstrap_clients)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ListBootstrapClientsResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (bootstrap_clients != other.bootstrap_clients) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + bootstrap_clients.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (bootstrap_clients.isNotEmpty()) result += """bootstrap_clients=$bootstrap_clients"""
    return result.joinToString(prefix = "ListBootstrapClientsResponse{", separator = ", ", postfix =
        "}")
  }

  fun copy(bootstrap_clients: List<BootstrapClient> = this.bootstrap_clients,
      unknownFields: ByteString = this.unknownFields): ListBootstrapClientsResponse =
      ListBootstrapClientsResponse(bootstrap_clients, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ListBootstrapClientsResponse> = object :
        ProtoAdapter<ListBootstrapClientsResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ListBootstrapClientsResponse::class, 
      "type.googleapis.com/ListBootstrapClientsResponse", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ListBootstrapClientsResponse): Int {
        var size = value.unknownFields.size
        size += BootstrapClient.ADAPTER.asRepeated().encodedSizeWithTag(1, value.bootstrap_clients)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ListBootstrapClientsResponse) {
        BootstrapClient.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.bootstrap_clients)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ListBootstrapClientsResponse {
        val bootstrap_clients = mutableListOf<BootstrapClient>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> bootstrap_clients.add(BootstrapClient.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ListBootstrapClientsResponse(
          bootstrap_clients = bootstrap_clients,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ListBootstrapClientsResponse): ListBootstrapClientsResponse =
          value.copy(
        bootstrap_clients = value.bootstrap_clients.redactElements(BootstrapClient.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
