// Code generated by Wire protocol buffer compiler, do not edit.
// Source: NickservNick in nickserv.proto
package gg.strims.ppspp.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class NickservNick(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY
  )
  val id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY
  )
  val key: ByteString = ByteString.EMPTY,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val nick: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "remainingNameChangeQuota"
  )
  val remaining_name_change_quota: Int = 0,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "updatedTimestamp"
  )
  val updated_timestamp: Long = 0L,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "createdTimestamp"
  )
  val created_timestamp: Long = 0L,
  roles: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<NickservNick, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val roles: List<String> = immutableCopyOf("roles", roles)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NickservNick) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (key != other.key) return false
    if (nick != other.nick) return false
    if (remaining_name_change_quota != other.remaining_name_change_quota) return false
    if (updated_timestamp != other.updated_timestamp) return false
    if (created_timestamp != other.created_timestamp) return false
    if (roles != other.roles) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + key.hashCode()
      result = result * 37 + nick.hashCode()
      result = result * 37 + remaining_name_change_quota.hashCode()
      result = result * 37 + updated_timestamp.hashCode()
      result = result * 37 + created_timestamp.hashCode()
      result = result * 37 + roles.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=$id"""
    result += """key=$key"""
    result += """nick=${sanitize(nick)}"""
    result += """remaining_name_change_quota=$remaining_name_change_quota"""
    result += """updated_timestamp=$updated_timestamp"""
    result += """created_timestamp=$created_timestamp"""
    if (roles.isNotEmpty()) result += """roles=${sanitize(roles)}"""
    return result.joinToString(prefix = "NickservNick{", separator = ", ", postfix = "}")
  }

  fun copy(
    id: Long = this.id,
    key: ByteString = this.key,
    nick: String = this.nick,
    remaining_name_change_quota: Int = this.remaining_name_change_quota,
    updated_timestamp: Long = this.updated_timestamp,
    created_timestamp: Long = this.created_timestamp,
    roles: List<String> = this.roles,
    unknownFields: ByteString = this.unknownFields
  ): NickservNick = NickservNick(id, key, nick, remaining_name_change_quota, updated_timestamp,
      created_timestamp, roles, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<NickservNick> = object : ProtoAdapter<NickservNick>(
      FieldEncoding.LENGTH_DELIMITED, 
      NickservNick::class, 
      "type.googleapis.com/NickservNick", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: NickservNick): Int {
        var size = value.unknownFields.size
        if (value.id != 0L) size += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.id)
        if (value.key != ByteString.EMPTY) size += ProtoAdapter.BYTES.encodedSizeWithTag(2,
            value.key)
        if (value.nick != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.nick)
        if (value.remaining_name_change_quota != 0) size +=
            ProtoAdapter.UINT32.encodedSizeWithTag(4, value.remaining_name_change_quota)
        if (value.updated_timestamp != 0L) size += ProtoAdapter.UINT64.encodedSizeWithTag(5,
            value.updated_timestamp)
        if (value.created_timestamp != 0L) size += ProtoAdapter.UINT64.encodedSizeWithTag(6,
            value.created_timestamp)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(7, value.roles)
        return size
      }

      override fun encode(writer: ProtoWriter, value: NickservNick) {
        if (value.id != 0L) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.id)
        if (value.key != ByteString.EMPTY) ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.key)
        if (value.nick != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.nick)
        if (value.remaining_name_change_quota != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 4,
            value.remaining_name_change_quota)
        if (value.updated_timestamp != 0L) ProtoAdapter.UINT64.encodeWithTag(writer, 5,
            value.updated_timestamp)
        if (value.created_timestamp != 0L) ProtoAdapter.UINT64.encodeWithTag(writer, 6,
            value.created_timestamp)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 7, value.roles)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): NickservNick {
        var id: Long = 0L
        var key: ByteString = ByteString.EMPTY
        var nick: String = ""
        var remaining_name_change_quota: Int = 0
        var updated_timestamp: Long = 0L
        var created_timestamp: Long = 0L
        val roles = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.UINT64.decode(reader)
            2 -> key = ProtoAdapter.BYTES.decode(reader)
            3 -> nick = ProtoAdapter.STRING.decode(reader)
            4 -> remaining_name_change_quota = ProtoAdapter.UINT32.decode(reader)
            5 -> updated_timestamp = ProtoAdapter.UINT64.decode(reader)
            6 -> created_timestamp = ProtoAdapter.UINT64.decode(reader)
            7 -> roles.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return NickservNick(
          id = id,
          key = key,
          nick = nick,
          remaining_name_change_quota = remaining_name_change_quota,
          updated_timestamp = updated_timestamp,
          created_timestamp = created_timestamp,
          roles = roles,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: NickservNick): NickservNick = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
