// Code generated by Wire protocol buffer compiler, do not edit.
// Source: StartHLSEgressResponse in video.proto
package gg.strims.ppspp.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class StartHLSEgressResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY
  )
  val id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val url: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<StartHLSEgressResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StartHLSEgressResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (url != other.url) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + url.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=$id"""
    result += """url=${sanitize(url)}"""
    return result.joinToString(prefix = "StartHLSEgressResponse{", separator = ", ", postfix = "}")
  }

  fun copy(
    id: Long = this.id,
    url: String = this.url,
    unknownFields: ByteString = this.unknownFields
  ): StartHLSEgressResponse = StartHLSEgressResponse(id, url, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<StartHLSEgressResponse> = object :
        ProtoAdapter<StartHLSEgressResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      StartHLSEgressResponse::class, 
      "type.googleapis.com/StartHLSEgressResponse", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: StartHLSEgressResponse): Int {
        var size = value.unknownFields.size
        if (value.id != 0L) size += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.id)
        if (value.url != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.url)
        return size
      }

      override fun encode(writer: ProtoWriter, value: StartHLSEgressResponse) {
        if (value.id != 0L) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.id)
        if (value.url != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.url)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): StartHLSEgressResponse {
        var id: Long = 0L
        var url: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.UINT64.decode(reader)
            2 -> url = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StartHLSEgressResponse(
          id = id,
          url = url,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: StartHLSEgressResponse): StartHLSEgressResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
