// Code generated by Wire protocol buffer compiler, do not edit.
// Source: strims.profile.v1.ListProfilesResponse in profile/v1/profile.proto
package gg.strims.profile.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

class ListProfilesResponse(
  profiles: List<ProfileSummary> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ListProfilesResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "gg.strims.profile.v1.ProfileSummary#ADAPTER",
    label = WireField.Label.REPEATED
  )
  val profiles: List<ProfileSummary> = immutableCopyOf("profiles", profiles)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ListProfilesResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (profiles != other.profiles) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + profiles.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (profiles.isNotEmpty()) result += """profiles=$profiles"""
    return result.joinToString(prefix = "ListProfilesResponse{", separator = ", ", postfix = "}")
  }

  fun copy(profiles: List<ProfileSummary> = this.profiles, unknownFields: ByteString =
      this.unknownFields): ListProfilesResponse = ListProfilesResponse(profiles, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ListProfilesResponse> = object : ProtoAdapter<ListProfilesResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ListProfilesResponse::class, 
      "type.googleapis.com/strims.profile.v1.ListProfilesResponse", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ListProfilesResponse): Int {
        var size = value.unknownFields.size
        size += ProfileSummary.ADAPTER.asRepeated().encodedSizeWithTag(1, value.profiles)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ListProfilesResponse) {
        ProfileSummary.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.profiles)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ListProfilesResponse {
        val profiles = mutableListOf<ProfileSummary>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> profiles.add(ProfileSummary.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ListProfilesResponse(
          profiles = profiles,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ListProfilesResponse): ListProfilesResponse = value.copy(
        profiles = value.profiles.redactElements(ProfileSummary.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
