// Code generated by Wire protocol buffer compiler, do not edit.
// Source: strims.network.v1.TestDirectoryPublishRequest in network/v1/directory.proto
package gg.strims.network.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class TestDirectoryPublishRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "networkKey"
  )
  val network_key: ByteString = ByteString.EMPTY,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<TestDirectoryPublishRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TestDirectoryPublishRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (network_key != other.network_key) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + network_key.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """network_key=$network_key"""
    return result.joinToString(prefix = "TestDirectoryPublishRequest{", separator = ", ", postfix =
        "}")
  }

  fun copy(network_key: ByteString = this.network_key, unknownFields: ByteString =
      this.unknownFields): TestDirectoryPublishRequest = TestDirectoryPublishRequest(network_key,
      unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<TestDirectoryPublishRequest> = object :
        ProtoAdapter<TestDirectoryPublishRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      TestDirectoryPublishRequest::class, 
      "type.googleapis.com/strims.network.v1.TestDirectoryPublishRequest", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: TestDirectoryPublishRequest): Int {
        var size = value.unknownFields.size
        if (value.network_key != ByteString.EMPTY) size += ProtoAdapter.BYTES.encodedSizeWithTag(1,
            value.network_key)
        return size
      }

      override fun encode(writer: ProtoWriter, value: TestDirectoryPublishRequest) {
        if (value.network_key != ByteString.EMPTY) ProtoAdapter.BYTES.encodeWithTag(writer, 1,
            value.network_key)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): TestDirectoryPublishRequest {
        var network_key: ByteString = ByteString.EMPTY
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> network_key = ProtoAdapter.BYTES.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TestDirectoryPublishRequest(
          network_key = network_key,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: TestDirectoryPublishRequest): TestDirectoryPublishRequest =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
