import { PassThrough } from "stream";

import { Message } from "../../../apis/strims/chat/v1/chat";

const history = [
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599345629214,"data":"Ph4t3 I sentence you to 10 years in body shaming jail PepoBan","entities":{"emotes":[{"name":"PepoBan","bounds":{"start":54,"end":61}}],"nicks":[{"nick":"Ph4t3","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"Xymos","features":[],"timestamp":1599345636022,"data":"soMuchForSubtlety Jbpratt sounds like a valid reason SHRUG:fast","entities":{"emotes":[{"name":"SHRUG","bounds":{"start":53,"end":63},"modifiers":["fast"]}]}}',
  'MSG {"nick":"SoMuchForSubtlety","features":[],"timestamp":1599345648052,"data":"jbpratt  and the documentation is completely shit too PepeLaugh","entities":{"emotes":[{"name":"PepeLaugh","bounds":{"start":54,"end":63}}],"nicks":[{"nick":"jbpratt","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"jbpratt","features":[],"timestamp":1599345650707,"data":"Xymos UWOTM8 does it","entities":{"emotes":[{"name":"UWOTM8","bounds":{"start":6,"end":12}}],"nicks":[{"nick":"Xymos","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"Xymos","features":[],"timestamp":1599345658816,"data":"Jbpratt to kys","entities":{}}',
  'MSG {"nick":"Ph4t3","features":[],"timestamp":1599345665717,"data":"guwapguwapguwap shame me daddy gachiGASM","entities":{"emotes":[{"name":"gachiGASM","bounds":{"start":31,"end":40}}],"nicks":[{"nick":"guwapguwapguwap","bounds":{"start":0,"end":15}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599345668528,"data":"DANKMEMES","entities":{"emotes":[{"name":"DANKMEMES","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599345668739,"data":"TsoChicken FeelsWeirdMan","entities":{"emotes":[{"name":"FeelsWeirdMan","bounds":{"start":11,"end":24}}],"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599345674628,"data":"Deadwing PeepoWeird","entities":{"emotes":[{"name":"PeepoWeird","bounds":{"start":9,"end":19}}],"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599345675661,"data":"https://strims.gg/angelthump/windowsmoviehouse gachiGASM","entities":{"links":[{"url":"https://strims.gg/angelthump/windowsmoviehouse","bounds":{"start":0,"end":46}}],"emotes":[{"name":"gachiGASM","bounds":{"start":47,"end":56}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599345681097,"data":"GODMAN","entities":{"emotes":[{"name":"GODMAN","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599345689649,"data":"incomes zhukov GODMAN","entities":{"emotes":[{"name":"GODMAN","bounds":{"start":15,"end":21}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599345691790,"data":"the zhuk","entities":{}}',
  'MSG {"nick":"Nopileus","features":[],"timestamp":1599345691805,"data":"big dick zhukov LUL","entities":{"emotes":[{"name":"LUL","bounds":{"start":16,"end":19}}]}}',
  'MSG {"nick":"shi___","features":[],"timestamp":1599345696862,"data":"PepeHands kirby isn\'t here to watch his team lose","entities":{"emotes":[{"name":"PepeHands","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599345701663,"data":"the zhukk Kreygasm","entities":{"emotes":[{"name":"Kreygasm","bounds":{"start":10,"end":18}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599345766035,"data":"TsoChicken I could 100% see Google promising to pay like $2000 a year to a family if they named their child Google and let Google check in every now and then for publicity stunts LUL","entities":{"emotes":[{"name":"LUL","bounds":{"start":179,"end":182}}],"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599345776899,"data":"TsoChicken \\"that\'s more than my husband\'s salary, yes!\\"","entities":{"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599345810520,"data":"this is my son","entities":{}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599345840551,"data":"TeslaHermesRyzenFleshlight","entities":{}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599345844946,"data":"PepOk","entities":{"emotes":[{"name":"PepOk","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599345879083,"data":"Deadwing EZ advertisement","entities":{"emotes":[{"name":"EZ","bounds":{"start":9,"end":11}}],"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"erik","features":[],"timestamp":1599345879957,"data":"Hhhehhehe","entities":{"emotes":[{"name":"Hhhehhehe","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"decoiii","features":[],"timestamp":1599345882693,"data":"!embed https://www.youtube.com/watch?v=Wqw_6RkXMJ8\\u0026t=0s","entities":{"links":[{"url":"https://www.youtube.com/watch?v=Wqw_6RkXMJ8\\u0026t=0s","bounds":{"start":7,"end":55}}]}}',
  'MSG {"nick":"Bot","features":["moderator","bot"],"timestamp":1599345882709,"data":"strims.gg/youtube/Wqw_6RkXMJ8","entities":{"links":[{"url":"strims.gg/youtube/Wqw_6RkXMJ8","bounds":{"start":0,"end":29}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599345888489,"data":"Deadwing whats up google Pepega","entities":{"emotes":[{"name":"Pepega","bounds":{"start":25,"end":31}}],"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599345923679,"data":"I should write a short story about sthis shit lmao","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599345929262,"data":"I\'m sure something like it already exists though","entities":{}}',
  'MSG {"nick":"Viscosity","features":[],"timestamp":1599345994189,"data":"toronto Abathur","entities":{"emotes":[{"name":"Abathur","bounds":{"start":8,"end":15}}]}}',
  'MSG {"nick":"shi___","features":[],"timestamp":1599346041801,"data":"Viscosity PepeHands i like them but their gonna lose","entities":{"emotes":[{"name":"PepeHands","bounds":{"start":10,"end":19}}],"nicks":[{"nick":"Viscosity","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346045065,"data":"LUL","entities":{"emotes":[{"name":"LUL","bounds":{"start":0,"end":3}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599346054709,"data":"Gehirnchirurg swap with me","entities":{"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"Viscosity","features":[],"timestamp":1599346055529,"data":"shi___ anyone but boston SOTRIGGERED","entities":{"emotes":[{"name":"SOTRIGGERED","bounds":{"start":25,"end":36}}],"nicks":[{"nick":"shi___","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346057385,"data":"Deadwing 2020, the year memes killed society GODMAN best selling oprah bookclub on amazon","entities":{"emotes":[{"name":"GODMAN","bounds":{"start":45,"end":51}}],"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346061178,"data":"Nept no PeepoWeird","entities":{"emotes":[{"name":"PeepoWeird","bounds":{"start":8,"end":18}}],"nicks":[{"nick":"Nept","bounds":{"start":0,"end":4}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346069145,"data":"OverRustle","entities":{"emotes":[{"name":"OverRustle","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599346069557,"data":"Gehirnchirurg JUST SWAP WITH ME","entities":{"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599346077629,"data":"TsoChicken reminder","entities":{"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"shi___","features":[],"timestamp":1599346083820,"data":"Viscosity FeelsOkayMan bos is my second team that left","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":10,"end":22}}],"nicks":[{"nick":"Viscosity","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599346084143,"data":"TsoChicken there\'s a movie about Pepe the Frog.","entities":{"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346089818,"data":"Deadwing EZ","entities":{"emotes":[{"name":"EZ","bounds":{"start":9,"end":11}}],"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346101303,"data":"DuckerZ:hyper","entities":{"emotes":[{"name":"DuckerZ","modifiers":["hyper"],"bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"coolkumquat","features":[],"timestamp":1599346115453,"data":"why was ufc delayed","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599346120203,"data":"LCS","entities":{}}',
  'MSG {"nick":"chihayalove72","features":[],"timestamp":1599346123919,"data":"coolkumquat corona","entities":{"nicks":[{"nick":"coolkumquat","bounds":{"start":0,"end":11}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346132848,"data":"fucking zhukov LUL","entities":{"emotes":[{"name":"LUL","bounds":{"start":15,"end":18}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346186564,"data":"coolkumquat why watch ufc when you can watch the real thing at one of the protests PEPE","entities":{"emotes":[{"name":"PEPE","bounds":{"start":83,"end":87}}],"nicks":[{"nick":"coolkumquat","bounds":{"start":0,"end":11}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346188414,"data":"I will not be squeezed OverRustle","entities":{"emotes":[{"name":"OverRustle","bounds":{"start":23,"end":33}}]}}',
  'MSG {"nick":"ulmo22","features":[],"timestamp":1599346213566,"data":"coolkumquat whose fighting","entities":{"nicks":[{"nick":"coolkumquat","bounds":{"start":0,"end":11}}]}}',
  'MSG {"nick":"ENEMIES","features":[],"timestamp":1599346226598,"data":"catJAM","entities":{"emotes":[{"name":"catJAM","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346230800,"data":"OMEGALUL https://i.redd.it/3v0eyszlucl51.jpg","entities":{"links":[{"url":"https://i.redd.it/3v0eyszlucl51.jpg","bounds":{"start":9,"end":44}}],"emotes":[{"name":"OMEGALUL","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"shi___","features":[],"timestamp":1599346240137,"data":"TsoChicken NoTears based opinion, plus fights are better when people hate each other","entities":{"emotes":[{"name":"NoTears","bounds":{"start":11,"end":18}}],"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"coolkumquat","features":[],"timestamp":1599346241957,"data":"ulmo22 your mom","entities":{"nicks":[{"nick":"ulmo22","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346252451,"data":"shi___ plus they use weapons GODMAN","entities":{"emotes":[{"name":"GODMAN","bounds":{"start":29,"end":35}}],"nicks":[{"nick":"shi___","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"ulmo22","features":[],"timestamp":1599346255206,"data":"coolkumquat PepeMods","entities":{"emotes":[{"name":"PepeMods","bounds":{"start":12,"end":20}}],"nicks":[{"nick":"coolkumquat","bounds":{"start":0,"end":11}}]}}',
  'MSG {"nick":"Versicarius","features":[],"timestamp":1599346257990,"data":"Xymos bedtime","entities":{"nicks":[{"nick":"Xymos","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599346334228,"data":"https://old.reddit.com/r/LivestreamFail/comments/imzqr1/clint_stevens_talks_about_his_first_time_having/ wtf there are people who plan out moves and not just spam buttons to get the higest combo BASEDWATM8","entities":{"links":[{"url":"https://old.reddit.com/r/LivestreamFail/comments/imzqr1/clint_stevens_talks_about_his_first_time_having/","bounds":{"start":0,"end":104}}],"emotes":[{"name":"BASEDWATM8","bounds":{"start":195,"end":205}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346390397,"data":"gachiGASM:hyper Clap nsfw https://www.reddit.com/r/funny/comments/in53yv/peekaboo/","entities":{"links":[{"url":"https://www.reddit.com/r/funny/comments/in53yv/peekaboo/","bounds":{"start":26,"end":82}}],"emotes":[{"name":"gachiGASM","modifiers":["hyper"],"bounds":{"start":0,"end":15}},{"name":"Clap","bounds":{"start":16,"end":20}}],"tags":[{"name":"nsfw","bounds":{"start":21,"end":25}}]}}',
  'MSG {"nick":"globburt","features":[],"timestamp":1599346449566,"data":"Lowry GODMAN","entities":{"emotes":[{"name":"GODMAN","bounds":{"start":6,"end":12}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346544221,"data":"LUL","entities":{"emotes":[{"name":"LUL","bounds":{"start":0,"end":3}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346558903,"data":"DuckerZ","entities":{"emotes":[{"name":"DuckerZ","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346567917,"data":"wet box DuckerZ","entities":{"emotes":[{"name":"DuckerZ","bounds":{"start":8,"end":15}}]}}',
  'MSG {"nick":"Metronome","features":[],"timestamp":1599346594397,"data":"TsoChicken whale tail is perfect for me","entities":{"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346632739,"data":"Metronome gachiGASM Clap","entities":{"emotes":[{"name":"gachiGASM","bounds":{"start":10,"end":19}},{"name":"Clap","bounds":{"start":20,"end":24}}],"nicks":[{"nick":"Metronome","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346633056,"data":"monkaMEGA","entities":{"emotes":[{"name":"monkaMEGA","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599346643261,"data":"KEKW","entities":{"emotes":[{"name":"KEKW","bounds":{"start":0,"end":4}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346644024,"data":"Hhhehhehe","entities":{"emotes":[{"name":"Hhhehhehe","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346645434,"data":"Hhhehhehe","entities":{"emotes":[{"name":"Hhhehhehe","bounds":{"start":0,"end":9},"combo":2}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599346649362,"data":"death of stalin is such a dank movie","entities":{}}',
  'MSG {"nick":"ulmo22","features":[],"timestamp":1599346710872,"data":"t5tv where did the music go","entities":{}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346730499,"data":"GREED:worth https://www.treasury.gov/tigta/auditreports/2020reports/202030015fr.pdf","entities":{"links":[{"url":"https://www.treasury.gov/tigta/auditreports/2020reports/202030015fr.pdf","bounds":{"start":12,"end":83}}],"emotes":[{"name":"GREED","modifiers":["worth"],"bounds":{"start":0,"end":11}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346764790,"data":"TsoChicken PepoG","entities":{"emotes":[{"name":"PepoG","bounds":{"start":11,"end":16}}],"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599346820607,"data":"Baria\'s memory is GODMAN","entities":{"emotes":[{"name":"GODMAN","bounds":{"start":18,"end":24}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346824119,"data":"\\u003eaccurate depiction of chatter who digs up year old logs PepoG","entities":{"emotes":[{"name":"PepoG","bounds":{"start":57,"end":62}}],"greenText":{"bounds":{"start":0,"end":62}}}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599346857983,"data":"Gehirnchirurg you said bad words, don\'t you PeepoWeird","entities":{"emotes":[{"name":"PeepoWeird","bounds":{"start":44,"end":54}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"globburt","features":[],"timestamp":1599346865089,"data":"Gasol\'s scoring ECH","entities":{"emotes":[{"name":"ECH","bounds":{"start":16,"end":19}}]}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346867089,"data":"Gehirnchirurg and an accurate depiction of the consequences SOTRIGGERED","entities":{"emotes":[{"name":"SOTRIGGERED","bounds":{"start":60,"end":71}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599346890363,"data":"oo nice play","entities":{}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346896182,"data":"Of_Odin if you mean \'nigger\', nope. I never used that word in a inappropriate context NoTears","entities":{"emotes":[{"name":"NoTears","bounds":{"start":86,"end":93}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599346912858,"data":"guwapguwapguwap SWEATY chat plots agains the chatter? SWEATY","entities":{"emotes":[{"name":"SWEATY","bounds":{"start":16,"end":22}},{"name":"SWEATY","bounds":{"start":54,"end":60}}],"nicks":[{"nick":"guwapguwapguwap","bounds":{"start":0,"end":15}}]}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599346941822,"data":"holy fuck gasol sleeping","entities":{}}',
  'MSG {"nick":"guwapguwapguwap","features":[],"timestamp":1599346946946,"data":"Gehirnchirurg yes, and then... PEPE","entities":{"emotes":[{"name":"PEPE","bounds":{"start":31,"end":35}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346947501,"data":"Kreygasm https://clips.twitch.tv/TriangularFrozenGorillaCmonBruh","entities":{"links":[{"url":"https://clips.twitch.tv/TriangularFrozenGorillaCmonBruh","bounds":{"start":9,"end":64}}],"emotes":[{"name":"Kreygasm","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346964367,"data":"2025 games are going to be nuts","entities":{}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599346966604,"data":"Kreygasm","entities":{"emotes":[{"name":"Kreygasm","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"giantcookie","features":[],"timestamp":1599346987958,"data":"nick nurse is so fucking annoying","entities":{}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599346991547,"data":"TsoChicken minus 60 fps for marginally better looking shadows FeelsOkayMan","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":62,"end":74}}],"nicks":[{"nick":"TsoChicken","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"giantcookie","features":[],"timestamp":1599346992523,"data":"cant stand looking at that guy","entities":{}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599347015855,"data":"Chehgo PEPE","entities":{"emotes":[{"name":"PEPE","bounds":{"start":7,"end":11}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347031734,"data":"Nept you are a cub Wowee","entities":{"emotes":[{"name":"Wowee","bounds":{"start":19,"end":24}}],"nicks":[{"nick":"Nept","bounds":{"start":0,"end":4}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599347041318,"data":"Gehirnchirurg WEEWOO you just did","entities":{"emotes":[{"name":"WEEWOO","bounds":{"start":14,"end":20}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599347044567,"data":"i cant believe people play games with shadows on PepeLaugh","entities":{"emotes":[{"name":"PepeLaugh","bounds":{"start":49,"end":58}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347057575,"data":"Of_Odin that was an example for when there is nothing wrong with it NoTears","entities":{"emotes":[{"name":"NoTears","bounds":{"start":68,"end":75}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599347068691,"data":"Gehirnchirurg Wowee","entities":{"emotes":[{"name":"Wowee","bounds":{"start":14,"end":19}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347083385,"data":"Of_Odin unless ofc you believe that the word is like the name voldemort and cant be said aloud NoTears","entities":{"emotes":[{"name":"NoTears","bounds":{"start":95,"end":102}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347087385,"data":"Chehgo there\'s a lot of room to move to facilitate better lighting now though with how much computational power is saved in UE5","entities":{"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347105888,"data":"Chehgo that engine\'s efficiency is through the roof from what we know about it","entities":{"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599347138769,"data":"Deadwing rtx is still a different thing i assume monkaHmm","entities":{"emotes":[{"name":"monkaHmm","bounds":{"start":49,"end":57}}],"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347181236,"data":"Chehgo it is, but I\'d assume there are optimizations made around it in the Unreal Engine. That was, after all, an Unreal demo they were doing (one would assume, judging by the stream info)","entities":{"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599347228967,"data":"Gehirnchirurg doubling down I see PEPE","entities":{"emotes":[{"name":"PEPE","bounds":{"start":34,"end":38}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347266228,"data":"Of_Odin always double down on reasonable positions FeelsOkayMan","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":51,"end":63}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599347271262,"data":"Deadwing high performance with that kind of lighting will probably not be affordable for many people for 1-2 generations still","entities":{"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599347283100,"data":"Gehirnchirurg \\\\ Wowee /","entities":{"emotes":[{"name":"Wowee","bounds":{"start":16,"end":21}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347285958,"data":"PeepoHappy Nept","entities":{"emotes":[{"name":"PeepoHappy","bounds":{"start":0,"end":10}}],"nicks":[{"nick":"Nept","bounds":{"start":11,"end":15}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599347290836,"data":"PeepoHappy","entities":{"emotes":[{"name":"PeepoHappy","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347310554,"data":"Chehgo nope, but it\'s still a pretty big step in that affordability.","entities":{"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347311233,"data":"\\u003etfw you will never get a shoutout from stalin\'s son FeelsBadMan","entities":{"emotes":[{"name":"FeelsBadMan","bounds":{"start":53,"end":64}}],"greenText":{"bounds":{"start":0,"end":64}}}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347327158,"data":"Chehgo at the very least we can watch streams of dank-looking games PeepoHappy","entities":{"emotes":[{"name":"PeepoHappy","bounds":{"start":68,"end":78}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599347349711,"data":"Deadwing not with youtube compression at least KEKW","entities":{"emotes":[{"name":"KEKW","bounds":{"start":47,"end":51}}],"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599347358576,"data":"why does taco fall not play?","entities":{}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599347373581,"data":"Gehirnchirurg I imagine you guys were mentioned in a few of their speeches PEPE","entities":{"emotes":[{"name":"PEPE","bounds":{"start":75,"end":79}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347376469,"data":"Chehgo Twitch is pretty good though","entities":{"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347392047,"data":"Nept that was a different germany ok PEPE","entities":{"emotes":[{"name":"PEPE","bounds":{"start":37,"end":41}}],"nicks":[{"nick":"Nept","bounds":{"start":0,"end":4}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599347394197,"data":"Deadwing you\'re pretty good though","entities":{"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347404205,"data":"SEMPAI","entities":{"emotes":[{"name":"SEMPAI","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599347409384,"data":"Deadwing the only streamers i regularly watch still stream in 720p KEKW","entities":{"emotes":[{"name":"KEKW","bounds":{"start":67,"end":71}}],"nicks":[{"nick":"Deadwing","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347431314,"data":"oh dang","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347443135,"data":"well I guess none of the rest of us can watch or play next-gen-graphics games PepeHands","entities":{"emotes":[{"name":"PepeHands","bounds":{"start":78,"end":87}}]}}',
  'MSG {"nick":"chihayalove72","features":[],"timestamp":1599347444793,"data":"UFC starting https://strims.gg/angelthump/chihayalove72","entities":{"links":[{"url":"https://strims.gg/angelthump/chihayalove72","bounds":{"start":13,"end":55}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599347452987,"data":"KEKW","entities":{"emotes":[{"name":"KEKW","bounds":{"start":0,"end":4}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347535412,"data":"Uhhhhhhh","entities":{}}',
  'MSG {"nick":"TsoChicken","features":[],"timestamp":1599347535656,"data":"someone should take all this new tech, make a sick looking AAA quality game based in present day D.C where you walk around and play solitaire at different locations Kreygasm","entities":{"emotes":[{"name":"Kreygasm","bounds":{"start":165,"end":173}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347536343,"data":"Hm.","entities":{}}',
  'MSG {"nick":"spydrzZ","features":[],"timestamp":1599347539205,"data":"wtf is that beard","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347540848,"data":"Jensen picking-up Zilean.","entities":{}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599347570975,"data":"spydrzZ same style as zabit","entities":{"nicks":[{"nick":"spydrzZ","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Abudhabbi","features":[],"timestamp":1599347590277,"data":"Doublelift senna again PepeMods","entities":{"emotes":[{"name":"PepeMods","bounds":{"start":23,"end":31}}]}}',
  'MSG {"nick":"dragopie","features":[],"timestamp":1599347591184,"data":"PepoComfy","entities":{"emotes":[{"name":"PepoComfy","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347591397,"data":"TL picking-up Voli here?","entities":{}}',
  'MSG {"nick":"spydrzZ","features":[],"timestamp":1599347599613,"data":"is way darker then his hair, and he shaved the sides, looks trash","entities":{}}',
  'MSG {"nick":"ender9","features":[],"timestamp":1599347601996,"data":"who is this announcer ?????","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347621179,"data":"Naut is good","entities":{}}',
  'MSG {"nick":"ENEMIES","features":[],"timestamp":1599347636618,"data":"meow meow catJAM meow catJAM meow","entities":{"emotes":[{"name":"catJAM","bounds":{"start":10,"end":16}},{"name":"catJAM","bounds":{"start":22,"end":28}}]}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347652303,"data":"oh TSM FUCKS","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347653061,"data":"lol","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347679858,"data":"ayyyy","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347681441,"data":"there\'s the Ornn","entities":{}}',
  'MSG {"nick":"Abudhabbi","features":[],"timestamp":1599347685874,"data":"Shen jungle?","entities":{}}',
  'MSG {"nick":"Abudhabbi","features":[],"timestamp":1599347691987,"data":"wtf is this draft","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347701092,"data":"Jungle Shen is fine","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347726066,"data":"I\'d have loved if it was Jungle Syndra","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347729616,"data":"that\'d have been funny as fuck","entities":{}}',
  'MSG {"nick":"Deadwing","features":[],"timestamp":1599347734491,"data":"and just completely abused by Lillia LUL","entities":{"emotes":[{"name":"LUL","bounds":{"start":37,"end":40}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347864674,"data":"DaFeels","entities":{"emotes":[{"name":"DaFeels","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599347867533,"data":"DaFeels","entities":{"emotes":[{"name":"DaFeels","bounds":{"start":0,"end":7},"combo":2}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347913492,"data":"PepeLaugh yep, thats def gonna be the last bit of internal turmoil in the soviet union","entities":{"emotes":[{"name":"PepeLaugh","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599347923753,"data":"Gehirnchirurg FeelsOkayMan we can put it behind us","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":14,"end":26}}],"nicks":[{"nick":"Gehirnchirurg","bounds":{"start":0,"end":13}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599347941270,"data":"Nept everything is going to be fine now FeelsOkayMan","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":40,"end":52}}],"nicks":[{"nick":"Nept","bounds":{"start":0,"end":4}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599347988647,"data":"the eyebrows on him tho PepeLaugh","entities":{"emotes":[{"name":"PepeLaugh","bounds":{"start":24,"end":33}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599348064326,"data":"so something happened on my schools canvas shit, and apparently everyone got added to some first year course and people just spammed the discussion pages sending hundreds of emails to everyone. and my friend linked me one of the emails he got","entities":{}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599348065611,"data":"\\u003eNeed 4 dps (pref ranged) and 2 heals for new world of warcraft expansion, no shamans or priests, must be able to raid 3 days a week, must have previous experience raiding at the highest level.\\n\\nNo gnomes allowed","entities":{"greenText":{"bounds":{"start":0,"end":212}}}}',
  'MSG {"nick":"Ftwpala","features":[],"timestamp":1599348072705,"data":"/me looks at Nept \'s eyebrows SPY","entities":{"emotes":[{"name":"SPY","bounds":{"start":30,"end":33}}],"nicks":[{"nick":"Nept","bounds":{"start":13,"end":17}}],"me":{"bounds":{"start":4,"end":33}}}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599348076882,"data":"imagine sending that with your name attached on a course fucking page OMEGALUL","entities":{"emotes":[{"name":"OMEGALUL","bounds":{"start":70,"end":78}}]}}',
  'MSG {"nick":"arkzats","features":[],"timestamp":1599348088363,"data":"Chehgo OMEGALUL","entities":{"emotes":[{"name":"OMEGALUL","bounds":{"start":7,"end":15}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"bikedog","features":[],"timestamp":1599348099123,"data":"Chehgo gnomes DuckerZ","entities":{"emotes":[{"name":"DuckerZ","bounds":{"start":14,"end":21}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Nept","features":[],"timestamp":1599348100704,"data":"Chehgo \\u003eno shamans or priests FeelsBadMan","entities":{"emotes":[{"name":"FeelsBadMan","bounds":{"start":30,"end":41}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348101358,"data":"Chehgo wtf LUL","entities":{"emotes":[{"name":"LUL","bounds":{"start":11,"end":14}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348113262,"data":"Nept yeah and yet they accept druids wtf SHRUG","entities":{"emotes":[{"name":"SHRUG","bounds":{"start":41,"end":46}}],"nicks":[{"nick":"Nept","bounds":{"start":0,"end":4}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348122744,"data":"Might as well refuse all hybrids PepeLaugh","entities":{"emotes":[{"name":"PepeLaugh","bounds":{"start":33,"end":42}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348165948,"data":"There\'s an alarm going off outside monkaMEGA","entities":{"emotes":[{"name":"monkaMEGA","bounds":{"start":35,"end":44}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599348177320,"data":"Chehgo its called taking the game serious you noob EZ","entities":{"emotes":[{"name":"EZ","bounds":{"start":51,"end":53}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Ftwpala","features":[],"timestamp":1599348177867,"data":"Nept umaruCry","entities":{"emotes":[{"name":"umaruCry","bounds":{"start":5,"end":13}}],"nicks":[{"nick":"Nept","bounds":{"start":0,"end":4}}]}}',
  'MSG {"nick":"Ftwpala","features":[],"timestamp":1599348219095,"data":"namemannen PeepoS","entities":{"emotes":[{"name":"PeepoS","bounds":{"start":11,"end":17}}],"nicks":[{"nick":"namemannen","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"ENEMIES","features":[],"timestamp":1599348241054,"data":"namemannen explosion imminent","entities":{"nicks":[{"nick":"namemannen","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"ENEMIES","features":[],"timestamp":1599348243066,"data":"POGGIES","entities":{"emotes":[{"name":"POGGIES","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348260554,"data":"ENEMIES POGGIES CampFire","entities":{"emotes":[{"name":"POGGIES","bounds":{"start":8,"end":15}},{"name":"CampFire","bounds":{"start":16,"end":24}}],"nicks":[{"nick":"ENEMIES","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"TUPACISALIVE69","features":[],"timestamp":1599348270067,"data":"penis","entities":{}}',
  'MSG {"nick":"ENEMIES","features":[],"timestamp":1599348276296,"data":"YEP","entities":{}}',
  'MSG {"nick":"j2y","features":[],"timestamp":1599348329883,"data":"penis","entities":{}}',
  'MSG {"nick":"RoseZerg","features":[],"timestamp":1599348330854,"data":"Ftwpala watch ufc with me PepoComfy","entities":{"emotes":[{"name":"PepoComfy","bounds":{"start":26,"end":35}}],"nicks":[{"nick":"Ftwpala","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Ftwpala","features":[],"timestamp":1599348354824,"data":"RoseZerg FeelsPepoMan:wide i have bad news || i really couldn\'t care less for UFC FeelsPepoMan:wide:hyper ||","entities":{"emotes":[{"name":"FeelsPepoMan","modifiers":["wide"],"bounds":{"start":9,"end":26}},{"name":"FeelsPepoMan","modifiers":["wide","hyper"],"bounds":{"start":82,"end":105}}],"nicks":[{"nick":"RoseZerg","bounds":{"start":0,"end":8}}],"spoilers":[{"bounds":{"start":43,"end":108}}]}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599348365401,"data":"whenis ufc","entities":{"nicks":[{"nick":"whenis","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"whenis","features":[],"timestamp":1599348366387,"data":"PepoG Fight Night 176: Overeem vs. Sakai started 26 minutes ago","entities":{"emotes":[{"name":"PepoG","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"mduncs","features":[],"timestamp":1599348379670,"data":"whenis f1","entities":{"nicks":[{"nick":"whenis","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"whenis","features":[],"timestamp":1599348380145,"data":"PepoG:wide FORMULA 1 GRAN PREMIO HEINEKEN D’ITALIA 2020 - RACE is in 13 hours and 44 minutes","entities":{"emotes":[{"name":"PepoG","modifiers":["wide"],"bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"RoseZerg","features":[],"timestamp":1599348383422,"data":"Ftwpala well i dont really care about this card NoTears","entities":{"emotes":[{"name":"NoTears","bounds":{"start":48,"end":55}}],"nicks":[{"nick":"Ftwpala","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"RoseZerg","features":[],"timestamp":1599348391135,"data":"gball are you here?","entities":{"nicks":[{"nick":"gball","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"Ftwpala","features":[],"timestamp":1599348393072,"data":"RoseZerg PeepoS what card","entities":{"emotes":[{"name":"PeepoS","bounds":{"start":9,"end":15}}],"nicks":[{"nick":"RoseZerg","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Ftwpala","features":[],"timestamp":1599348399366,"data":"RoseZerg RedCard ?","entities":{"emotes":[{"name":"RedCard","bounds":{"start":9,"end":16}}],"nicks":[{"nick":"RoseZerg","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Viscosity","features":[],"timestamp":1599348400139,"data":"Chehgo FeelsOkayMan","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":7,"end":19}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599348407290,"data":"Viscosity FeelsOkayMan","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":10,"end":22}}],"nicks":[{"nick":"Viscosity","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"decoiii","features":[],"timestamp":1599348414941,"data":"when is FD","entities":{}}',
  'MSG {"nick":"decoiii","features":[],"timestamp":1599348421966,"data":"whenis FD","entities":{"nicks":[{"nick":"whenis","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"whenis","features":[],"timestamp":1599348422319,"data":"PepoG No upcoming events found for \'FD\'","entities":{"emotes":[{"name":"PepoG","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"Gehirnchirurg","features":[],"timestamp":1599348480194,"data":"PepoComfy CampFire DJPepo:mirror https://www.youtube.com/watch?v=TIZWlW1YhbU","entities":{"links":[{"url":"https://www.youtube.com/watch?v=TIZWlW1YhbU","bounds":{"start":33,"end":76}}],"emotes":[{"name":"PepoComfy","bounds":{"start":0,"end":9}},{"name":"CampFire","bounds":{"start":10,"end":18}},{"name":"DJPepo","modifiers":["mirror"],"bounds":{"start":19,"end":32}}]}}',
  'MSG {"nick":"RoseZerg","features":[],"timestamp":1599348502119,"data":"Ftwpala ufc event tonight","entities":{"nicks":[{"nick":"Ftwpala","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"RoseZerg","features":[],"timestamp":1599348517778,"data":"refer to each differernt event as a \\"card\\"","entities":{}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599348533913,"data":"DAE Kobe guys","entities":{}}',
  'MSG {"nick":"Viscosity","features":[],"timestamp":1599348537873,"data":"Chehgo #PULLTHERIPCORD PeepoRiot","entities":{"emotes":[{"name":"PeepoRiot","bounds":{"start":23,"end":32}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599348542532,"data":"Viscosity PeepoRiot","entities":{"emotes":[{"name":"PeepoRiot","bounds":{"start":10,"end":19}}],"nicks":[{"nick":"Viscosity","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348542943,"data":"why are walmart pizzas so fucking shit, it\'s drying than the sahara REE","entities":{"emotes":[{"name":"REE","bounds":{"start":68,"end":71}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599348551115,"data":"Of_Odin what did you expect","entities":{"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"talentlesss","features":[],"timestamp":1599348563576,"data":"Viscosity  PeepoRiot  DUH GUH its the last resort duh guh my name ION :D:D:D:D","entities":{"emotes":[{"name":"PeepoRiot","bounds":{"start":11,"end":20}}],"nicks":[{"nick":"Viscosity","bounds":{"start":0,"end":9}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348563968,"data":"Chehgo not dry bullshit like digonrno REE","entities":{"emotes":[{"name":"REE","bounds":{"start":38,"end":41}}],"nicks":[{"nick":"Chehgo","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348566505,"data":"Of_Odin to be fair all supermarket pizzas are mediocre at best","entities":{"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348598358,"data":"the bottom of the crust feels like my cat\'s tounge, only dryer REE","entities":{"emotes":[{"name":"REE","bounds":{"start":63,"end":66}}]}}',
  'MSG {"nick":"decoiii","features":[],"timestamp":1599348599979,"data":"ALDI pizzza best pizza","entities":{}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348601901,"data":"Of_Odin one thing that can work pretty well tho is having frozen pizza dough","entities":{"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348612778,"data":"Of_Odin then you can make your own pretty fast POGGIES","entities":{"emotes":[{"name":"POGGIES","bounds":{"start":47,"end":54}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348623329,"data":"You can also make flammenküche","entities":{}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348632094,"data":"namemannen an hour isn\'t pretty fast PeepoWeird","entities":{"emotes":[{"name":"PeepoWeird","bounds":{"start":37,"end":47}}],"nicks":[{"nick":"namemannen","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599348637324,"data":"Of_Odin some frozen types are good but you need to know which","entities":{"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348640375,"data":"Of_Odin fair enough FeelsBadMan","entities":{"emotes":[{"name":"FeelsBadMan","bounds":{"start":20,"end":31}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"Pistolfied","features":[],"timestamp":1599348653039,"data":"BabyRage it was a deflection BabyRage PepeLaugh:fast","entities":{"emotes":[{"name":"BabyRage","bounds":{"start":0,"end":8}},{"name":"BabyRage","bounds":{"start":29,"end":37}},{"name":"PepeLaugh","bounds":{"start":38,"end":52},"modifiers":["fast"]}]}}',
  'MSG {"nick":"Pistolfied","features":[],"timestamp":1599348670801,"data":"guy just threw it off the court PepeLaugh","entities":{"emotes":[{"name":"PepeLaugh","bounds":{"start":32,"end":41}}]}}',
  'MSG {"nick":"globburt","features":[],"timestamp":1599348677972,"data":"Siakam PepeMods","entities":{"emotes":[{"name":"PepeMods","bounds":{"start":7,"end":15}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348685383,"data":"fucking wish I could find an empty bottle to spray some water on the bottom","entities":{}}',
  'MSG {"nick":"Versicarius","features":[],"timestamp":1599348685578,"data":"Xymos billyWeird","entities":{"emotes":[{"name":"billyWeird","bounds":{"start":6,"end":16}}],"nicks":[{"nick":"Xymos","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"Pistolfied","features":[],"timestamp":1599348689153,"data":"PepeMods","entities":{"emotes":[{"name":"PepeMods","bounds":{"start":0,"end":8}}]}}',
  'MSG {"nick":"Xymos","features":[],"timestamp":1599348691496,"data":"versicarius WHAT billyWeird:fast","entities":{"emotes":[{"name":"billyWeird","bounds":{"start":17,"end":32},"modifiers":["fast"]}]}}',
  'MSG {"nick":"Abudhabbi","features":[],"timestamp":1599348712687,"data":"TSM GODMAN","entities":{"emotes":[{"name":"GODMAN","bounds":{"start":4,"end":10}}]}}',
  'MSG {"nick":"Versicarius","features":[],"timestamp":1599348717418,"data":"Xymos 🛏","entities":{"nicks":[{"nick":"Xymos","bounds":{"start":0,"end":5}}]}}',
  'MSG {"nick":"Fatal","features":[],"timestamp":1599348806107,"data":"uhh","entities":{}}',
  'MSG {"nick":"Fatal","features":[],"timestamp":1599348808662,"data":"manamune senna?","entities":{}}',
  'MSG {"nick":"Fatal","features":[],"timestamp":1599348809564,"data":"y tho","entities":{}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348830252,"data":"my left mouse button and middle mouse button are both double clicking now PeepoWeird","entities":{"emotes":[{"name":"PeepoWeird","bounds":{"start":74,"end":84}}]}}',
  'MSG {"nick":"arkzats","features":[],"timestamp":1599348864753,"data":"Of_Odin quad DANKMEMES mouse","entities":{"emotes":[{"name":"DANKMEMES","bounds":{"start":13,"end":22}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348941418,"data":"Of_Odin I\'ve been wondering about why mice do that when they age, like does the debouncing circuit fail somehow, or mechanically the switch bounces more than the debouncer can handle? idk","entities":{"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599348943750,"data":"Of_Odin is it a razer KEKE","entities":{"emotes":[{"name":"KEKE","bounds":{"start":22,"end":26}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599348971461,"data":"blankspaceblank oh god I hope not I bought a razer mouse a few months ago and am happy with it PeepoWeird","entities":{"emotes":[{"name":"PeepoWeird","bounds":{"start":95,"end":105}}],"nicks":[{"nick":"blankspaceblank","bounds":{"start":0,"end":15}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348975327,"data":"namemannen its the spring wearing out, but Im too lazy to bend it","entities":{"nicks":[{"nick":"namemannen","bounds":{"start":0,"end":10}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348989097,"data":"blankspaceblank no, this is a zowie","entities":{"nicks":[{"nick":"blankspaceblank","bounds":{"start":0,"end":15}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599348997882,"data":"lasted almost 4 years","entities":{}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599349046615,"data":"4 years is good PepOk","entities":{"emotes":[{"name":"PepOk","bounds":{"start":16,"end":21}}]}}',
  'MSG {"nick":"mduncs","features":[],"timestamp":1599349046822,"data":"Of_Odin my genius move is to just click really hard until it stops exhibiting the behavior PepeComfy hasn\'t failed me yet","entities":{"emotes":[{"name":"PepeComfy","bounds":{"start":91,"end":100}}],"nicks":[{"nick":"Of_Odin","bounds":{"start":0,"end":7}}]}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599349054946,"data":"Yea every make will have that issue some get it within a year of heavy use some couple yrs","entities":{}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599349059948,"data":"mduncs I do the name PepeLaugh","entities":{"emotes":[{"name":"PepeLaugh","bounds":{"start":21,"end":30}}],"nicks":[{"nick":"mduncs","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"xoptimusprimatex","features":[],"timestamp":1599349074379,"data":"FeelsOkayMan","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":0,"end":12}}]}}',
  'MSG {"nick":"namemannen","features":[],"timestamp":1599349083271,"data":"mduncs Of_Odin what if you only do .5 clicks so then when it doubleclicks it becomes a single click weSmart","entities":{"emotes":[{"name":"weSmart","bounds":{"start":100,"end":107}}],"nicks":[{"nick":"mduncs","bounds":{"start":0,"end":6}},{"nick":"Of_Odin","bounds":{"start":7,"end":14}}]}}',
  'MSG {"nick":"Of_Odin","features":[],"timestamp":1599349096050,"data":"mduncs just doesn\'t really work on the mmb because this mouse as a really sluggish press","entities":{"nicks":[{"nick":"mduncs","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599349213217,"data":"If you\'re skilled with electronics then they\'re not hard to replace. Need some tools etc but prob not worth on a 5yr old mouse.","entities":{}}',
  'MSG {"nick":"Pistolfied","features":[],"timestamp":1599349232729,"data":"these basketball refs just call foul on literally anything LUL","entities":{"emotes":[{"name":"LUL","bounds":{"start":59,"end":62}}]}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599349239264,"data":"New ones are like $20 off aliexpress","entities":{}}',
  'MSG {"nick":"xoptimusprimatex","features":[],"timestamp":1599349241317,"data":"refs plan FeelsBadMan","entities":{"emotes":[{"name":"FeelsBadMan","bounds":{"start":10,"end":21}}]}}',
  'MSG {"nick":"xoptimusprimatex","features":[],"timestamp":1599349272879,"data":"siakam has less points then shots attempted PeepoWeird","entities":{"emotes":[{"name":"PeepoWeird","bounds":{"start":44,"end":54}}]}}',
  'MSG {"nick":"Pistolfied","features":[],"timestamp":1599349305098,"data":"these toronto 3s are awful KEKW","entities":{"emotes":[{"name":"KEKW","bounds":{"start":27,"end":31}}]}}',
  'MSG {"nick":"xoptimusprimatex","features":[],"timestamp":1599349318381,"data":"the 2\'s are even worse this game","entities":{}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599349325950,"data":"idk wtf is going on","entities":{}}',
  'MSG {"nick":"Pistolfied","features":[],"timestamp":1599349337628,"data":"both teams forgot how to play and can\'t score PepeLaugh","entities":{"emotes":[{"name":"PepeLaugh","bounds":{"start":46,"end":55}}]}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599349337778,"data":"raps so awkward","entities":{}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599349353983,"data":"brick fucking city","entities":{}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599349396611,"data":"finally holy shit","entities":{}}',
  'MSG {"nick":"Pistolfied","features":[],"timestamp":1599349399696,"data":"EZ","entities":{"emotes":[{"name":"EZ","bounds":{"start":0,"end":2}}]}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599349414142,"data":"Van elite","entities":{}}',
  'MSG {"nick":"shi___","features":[],"timestamp":1599349435544,"data":"trekxx OMEGALUL i could not imgaine raptors in the finals vs the best wing defenders clippers","entities":{"emotes":[{"name":"OMEGALUL","bounds":{"start":7,"end":15}}],"nicks":[{"nick":"trekxx","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"xoptimusprimatex","features":[],"timestamp":1599349439521,"data":"imagine if tatum got teched there OMEGALUL","entities":{"emotes":[{"name":"OMEGALUL","bounds":{"start":34,"end":42}}]}}',
  'MSG {"nick":"Chehgo","features":[],"timestamp":1599349449770,"data":"dc enjoying retirement FeelsOkayMan","entities":{"emotes":[{"name":"FeelsOkayMan","bounds":{"start":23,"end":35}}]}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599349450663,"data":"shi___  dude they would get fucking shit on OMEGALUL","entities":{"emotes":[{"name":"OMEGALUL","bounds":{"start":44,"end":52}}],"nicks":[{"nick":"shi___","bounds":{"start":0,"end":6}}]}}',
  'MSG {"nick":"blankspaceblank","features":[],"timestamp":1599349458805,"data":"Most teams are cold in the bubble. Even the Lakers","entities":{}}',
  'MSG {"nick":"trekxx","features":[],"timestamp":1599349465397,"data":"raptors playing like dogshit","entities":{}}',
];

type LegacyMessage = {
  nick: string;
  timestamp: number;
  data: string;
  entities: Message.IEntities;
};

export const messages = history
  .map((v) => JSON.parse(v.substr(4)) as unknown as LegacyMessage)
  .map(
    ({ nick, timestamp, data, entities }) =>
      new Message({
        nick: nick,
        // sentTime: BigInt(timestamp),
        serverTime: BigInt(timestamp),
        body: data,
        entities: new Message.Entities(entities),
      })
  );

class Emitter extends PassThrough {
  tid: number;
  i = 0;

  constructor(ivl: number = 5000, limit: number = Infinity) {
    super({ objectMode: true });
    this.tid = window.setInterval(() => {
      this.push(messages[this.i++ % history.length]);
      if (this.i >= limit) {
        clearInterval(this.tid);
      }
    }, ivl);
  }

  destroy(): void {
    clearInterval(this.tid);
    super.destroy();
  }
}

export default Emitter;
