// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SwarmEventType int32

const (
	SwarmEventType_CREATE_SWARM SwarmEventType = 0
	SwarmEventType_UPDATE_SWARM SwarmEventType = 1
	SwarmEventType_DELETE_SWARM SwarmEventType = 2
)

var SwarmEventType_name = map[int32]string{
	0: "CREATE_SWARM",
	1: "UPDATE_SWARM",
	2: "DELETE_SWARM",
}

var SwarmEventType_value = map[string]int32{
	"CREATE_SWARM": 0,
	"UPDATE_SWARM": 1,
	"DELETE_SWARM": 2,
}

func (x SwarmEventType) String() string {
	return proto.EnumName(SwarmEventType_name, int32(x))
}

func (SwarmEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type JoinSwarmRequest struct {
	SwarmUri             string   `protobuf:"bytes,1,opt,name=swarm_uri,json=swarmUri,proto3" json:"swarm_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinSwarmRequest) Reset()         { *m = JoinSwarmRequest{} }
func (m *JoinSwarmRequest) String() string { return proto.CompactTextString(m) }
func (*JoinSwarmRequest) ProtoMessage()    {}
func (*JoinSwarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *JoinSwarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSwarmRequest.Unmarshal(m, b)
}
func (m *JoinSwarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSwarmRequest.Marshal(b, m, deterministic)
}
func (m *JoinSwarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSwarmRequest.Merge(m, src)
}
func (m *JoinSwarmRequest) XXX_Size() int {
	return xxx_messageInfo_JoinSwarmRequest.Size(m)
}
func (m *JoinSwarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSwarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSwarmRequest proto.InternalMessageInfo

func (m *JoinSwarmRequest) GetSwarmUri() string {
	if m != nil {
		return m.SwarmUri
	}
	return ""
}

type JoinSwarmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinSwarmResponse) Reset()         { *m = JoinSwarmResponse{} }
func (m *JoinSwarmResponse) String() string { return proto.CompactTextString(m) }
func (*JoinSwarmResponse) ProtoMessage()    {}
func (*JoinSwarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *JoinSwarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSwarmResponse.Unmarshal(m, b)
}
func (m *JoinSwarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSwarmResponse.Marshal(b, m, deterministic)
}
func (m *JoinSwarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSwarmResponse.Merge(m, src)
}
func (m *JoinSwarmResponse) XXX_Size() int {
	return xxx_messageInfo_JoinSwarmResponse.Size(m)
}
func (m *JoinSwarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSwarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSwarmResponse proto.InternalMessageInfo

type LeaveSwarmRequest struct {
	SwarmUri             string   `protobuf:"bytes,1,opt,name=swarm_uri,json=swarmUri,proto3" json:"swarm_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveSwarmRequest) Reset()         { *m = LeaveSwarmRequest{} }
func (m *LeaveSwarmRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveSwarmRequest) ProtoMessage()    {}
func (*LeaveSwarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *LeaveSwarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveSwarmRequest.Unmarshal(m, b)
}
func (m *LeaveSwarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveSwarmRequest.Marshal(b, m, deterministic)
}
func (m *LeaveSwarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveSwarmRequest.Merge(m, src)
}
func (m *LeaveSwarmRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveSwarmRequest.Size(m)
}
func (m *LeaveSwarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveSwarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveSwarmRequest proto.InternalMessageInfo

func (m *LeaveSwarmRequest) GetSwarmUri() string {
	if m != nil {
		return m.SwarmUri
	}
	return ""
}

type LeaveSwarmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveSwarmResponse) Reset()         { *m = LeaveSwarmResponse{} }
func (m *LeaveSwarmResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveSwarmResponse) ProtoMessage()    {}
func (*LeaveSwarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *LeaveSwarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveSwarmResponse.Unmarshal(m, b)
}
func (m *LeaveSwarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveSwarmResponse.Marshal(b, m, deterministic)
}
func (m *LeaveSwarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveSwarmResponse.Merge(m, src)
}
func (m *LeaveSwarmResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveSwarmResponse.Size(m)
}
func (m *LeaveSwarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveSwarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveSwarmResponse proto.InternalMessageInfo

type GetIngressStreamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIngressStreamsRequest) Reset()         { *m = GetIngressStreamsRequest{} }
func (m *GetIngressStreamsRequest) String() string { return proto.CompactTextString(m) }
func (*GetIngressStreamsRequest) ProtoMessage()    {}
func (*GetIngressStreamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetIngressStreamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIngressStreamsRequest.Unmarshal(m, b)
}
func (m *GetIngressStreamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIngressStreamsRequest.Marshal(b, m, deterministic)
}
func (m *GetIngressStreamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIngressStreamsRequest.Merge(m, src)
}
func (m *GetIngressStreamsRequest) XXX_Size() int {
	return xxx_messageInfo_GetIngressStreamsRequest.Size(m)
}
func (m *GetIngressStreamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIngressStreamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIngressStreamsRequest proto.InternalMessageInfo

type GetIngressStreamsResponse struct {
	SwarmUri             string   `protobuf:"bytes,1,opt,name=swarm_uri,json=swarmUri,proto3" json:"swarm_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIngressStreamsResponse) Reset()         { *m = GetIngressStreamsResponse{} }
func (m *GetIngressStreamsResponse) String() string { return proto.CompactTextString(m) }
func (*GetIngressStreamsResponse) ProtoMessage()    {}
func (*GetIngressStreamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetIngressStreamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIngressStreamsResponse.Unmarshal(m, b)
}
func (m *GetIngressStreamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIngressStreamsResponse.Marshal(b, m, deterministic)
}
func (m *GetIngressStreamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIngressStreamsResponse.Merge(m, src)
}
func (m *GetIngressStreamsResponse) XXX_Size() int {
	return xxx_messageInfo_GetIngressStreamsResponse.Size(m)
}
func (m *GetIngressStreamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIngressStreamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIngressStreamsResponse proto.InternalMessageInfo

func (m *GetIngressStreamsResponse) GetSwarmUri() string {
	if m != nil {
		return m.SwarmUri
	}
	return ""
}

type StartHLSIngressRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartHLSIngressRequest) Reset()         { *m = StartHLSIngressRequest{} }
func (m *StartHLSIngressRequest) String() string { return proto.CompactTextString(m) }
func (*StartHLSIngressRequest) ProtoMessage()    {}
func (*StartHLSIngressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *StartHLSIngressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartHLSIngressRequest.Unmarshal(m, b)
}
func (m *StartHLSIngressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartHLSIngressRequest.Marshal(b, m, deterministic)
}
func (m *StartHLSIngressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartHLSIngressRequest.Merge(m, src)
}
func (m *StartHLSIngressRequest) XXX_Size() int {
	return xxx_messageInfo_StartHLSIngressRequest.Size(m)
}
func (m *StartHLSIngressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartHLSIngressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartHLSIngressRequest proto.InternalMessageInfo

type StartHLSIngressResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartHLSIngressResponse) Reset()         { *m = StartHLSIngressResponse{} }
func (m *StartHLSIngressResponse) String() string { return proto.CompactTextString(m) }
func (*StartHLSIngressResponse) ProtoMessage()    {}
func (*StartHLSIngressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *StartHLSIngressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartHLSIngressResponse.Unmarshal(m, b)
}
func (m *StartHLSIngressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartHLSIngressResponse.Marshal(b, m, deterministic)
}
func (m *StartHLSIngressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartHLSIngressResponse.Merge(m, src)
}
func (m *StartHLSIngressResponse) XXX_Size() int {
	return xxx_messageInfo_StartHLSIngressResponse.Size(m)
}
func (m *StartHLSIngressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartHLSIngressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartHLSIngressResponse proto.InternalMessageInfo

type StartHLSEgressRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartHLSEgressRequest) Reset()         { *m = StartHLSEgressRequest{} }
func (m *StartHLSEgressRequest) String() string { return proto.CompactTextString(m) }
func (*StartHLSEgressRequest) ProtoMessage()    {}
func (*StartHLSEgressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *StartHLSEgressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartHLSEgressRequest.Unmarshal(m, b)
}
func (m *StartHLSEgressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartHLSEgressRequest.Marshal(b, m, deterministic)
}
func (m *StartHLSEgressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartHLSEgressRequest.Merge(m, src)
}
func (m *StartHLSEgressRequest) XXX_Size() int {
	return xxx_messageInfo_StartHLSEgressRequest.Size(m)
}
func (m *StartHLSEgressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartHLSEgressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartHLSEgressRequest proto.InternalMessageInfo

type StartHLSEgressResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartHLSEgressResponse) Reset()         { *m = StartHLSEgressResponse{} }
func (m *StartHLSEgressResponse) String() string { return proto.CompactTextString(m) }
func (*StartHLSEgressResponse) ProtoMessage()    {}
func (*StartHLSEgressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *StartHLSEgressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartHLSEgressResponse.Unmarshal(m, b)
}
func (m *StartHLSEgressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartHLSEgressResponse.Marshal(b, m, deterministic)
}
func (m *StartHLSEgressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartHLSEgressResponse.Merge(m, src)
}
func (m *StartHLSEgressResponse) XXX_Size() int {
	return xxx_messageInfo_StartHLSEgressResponse.Size(m)
}
func (m *StartHLSEgressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartHLSEgressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartHLSEgressResponse proto.InternalMessageInfo

type StopHLSEgressRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopHLSEgressRequest) Reset()         { *m = StopHLSEgressRequest{} }
func (m *StopHLSEgressRequest) String() string { return proto.CompactTextString(m) }
func (*StopHLSEgressRequest) ProtoMessage()    {}
func (*StopHLSEgressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *StopHLSEgressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopHLSEgressRequest.Unmarshal(m, b)
}
func (m *StopHLSEgressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopHLSEgressRequest.Marshal(b, m, deterministic)
}
func (m *StopHLSEgressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopHLSEgressRequest.Merge(m, src)
}
func (m *StopHLSEgressRequest) XXX_Size() int {
	return xxx_messageInfo_StopHLSEgressRequest.Size(m)
}
func (m *StopHLSEgressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopHLSEgressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopHLSEgressRequest proto.InternalMessageInfo

type StopHLSEgressResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopHLSEgressResponse) Reset()         { *m = StopHLSEgressResponse{} }
func (m *StopHLSEgressResponse) String() string { return proto.CompactTextString(m) }
func (*StopHLSEgressResponse) ProtoMessage()    {}
func (*StopHLSEgressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *StopHLSEgressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopHLSEgressResponse.Unmarshal(m, b)
}
func (m *StopHLSEgressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopHLSEgressResponse.Marshal(b, m, deterministic)
}
func (m *StopHLSEgressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopHLSEgressResponse.Merge(m, src)
}
func (m *StopHLSEgressResponse) XXX_Size() int {
	return xxx_messageInfo_StopHLSEgressResponse.Size(m)
}
func (m *StopHLSEgressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopHLSEgressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopHLSEgressResponse proto.InternalMessageInfo

type MonitorSwarmsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorSwarmsRequest) Reset()         { *m = MonitorSwarmsRequest{} }
func (m *MonitorSwarmsRequest) String() string { return proto.CompactTextString(m) }
func (*MonitorSwarmsRequest) ProtoMessage()    {}
func (*MonitorSwarmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *MonitorSwarmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorSwarmsRequest.Unmarshal(m, b)
}
func (m *MonitorSwarmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorSwarmsRequest.Marshal(b, m, deterministic)
}
func (m *MonitorSwarmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorSwarmsRequest.Merge(m, src)
}
func (m *MonitorSwarmsRequest) XXX_Size() int {
	return xxx_messageInfo_MonitorSwarmsRequest.Size(m)
}
func (m *MonitorSwarmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorSwarmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorSwarmsRequest proto.InternalMessageInfo

type MonitorSwarmsResponse struct {
	Type                 SwarmEventType `protobuf:"varint,1,opt,name=type,proto3,enum=SwarmEventType" json:"type,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MonitorSwarmsResponse) Reset()         { *m = MonitorSwarmsResponse{} }
func (m *MonitorSwarmsResponse) String() string { return proto.CompactTextString(m) }
func (*MonitorSwarmsResponse) ProtoMessage()    {}
func (*MonitorSwarmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *MonitorSwarmsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorSwarmsResponse.Unmarshal(m, b)
}
func (m *MonitorSwarmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorSwarmsResponse.Marshal(b, m, deterministic)
}
func (m *MonitorSwarmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorSwarmsResponse.Merge(m, src)
}
func (m *MonitorSwarmsResponse) XXX_Size() int {
	return xxx_messageInfo_MonitorSwarmsResponse.Size(m)
}
func (m *MonitorSwarmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorSwarmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorSwarmsResponse proto.InternalMessageInfo

func (m *MonitorSwarmsResponse) GetType() SwarmEventType {
	if m != nil {
		return m.Type
	}
	return SwarmEventType_CREATE_SWARM
}

func (m *MonitorSwarmsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BootstrapDHTRequest struct {
	TransportUris        []string `protobuf:"bytes,1,rep,name=transport_uris,json=transportUris,proto3" json:"transport_uris,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootstrapDHTRequest) Reset()         { *m = BootstrapDHTRequest{} }
func (m *BootstrapDHTRequest) String() string { return proto.CompactTextString(m) }
func (*BootstrapDHTRequest) ProtoMessage()    {}
func (*BootstrapDHTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *BootstrapDHTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapDHTRequest.Unmarshal(m, b)
}
func (m *BootstrapDHTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapDHTRequest.Marshal(b, m, deterministic)
}
func (m *BootstrapDHTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapDHTRequest.Merge(m, src)
}
func (m *BootstrapDHTRequest) XXX_Size() int {
	return xxx_messageInfo_BootstrapDHTRequest.Size(m)
}
func (m *BootstrapDHTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapDHTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapDHTRequest proto.InternalMessageInfo

func (m *BootstrapDHTRequest) GetTransportUris() []string {
	if m != nil {
		return m.TransportUris
	}
	return nil
}

type BootstrapDHTResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootstrapDHTResponse) Reset()         { *m = BootstrapDHTResponse{} }
func (m *BootstrapDHTResponse) String() string { return proto.CompactTextString(m) }
func (*BootstrapDHTResponse) ProtoMessage()    {}
func (*BootstrapDHTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *BootstrapDHTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapDHTResponse.Unmarshal(m, b)
}
func (m *BootstrapDHTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapDHTResponse.Marshal(b, m, deterministic)
}
func (m *BootstrapDHTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapDHTResponse.Merge(m, src)
}
func (m *BootstrapDHTResponse) XXX_Size() int {
	return xxx_messageInfo_BootstrapDHTResponse.Size(m)
}
func (m *BootstrapDHTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapDHTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapDHTResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("SwarmEventType", SwarmEventType_name, SwarmEventType_value)
	proto.RegisterType((*JoinSwarmRequest)(nil), "JoinSwarmRequest")
	proto.RegisterType((*JoinSwarmResponse)(nil), "JoinSwarmResponse")
	proto.RegisterType((*LeaveSwarmRequest)(nil), "LeaveSwarmRequest")
	proto.RegisterType((*LeaveSwarmResponse)(nil), "LeaveSwarmResponse")
	proto.RegisterType((*GetIngressStreamsRequest)(nil), "GetIngressStreamsRequest")
	proto.RegisterType((*GetIngressStreamsResponse)(nil), "GetIngressStreamsResponse")
	proto.RegisterType((*StartHLSIngressRequest)(nil), "StartHLSIngressRequest")
	proto.RegisterType((*StartHLSIngressResponse)(nil), "StartHLSIngressResponse")
	proto.RegisterType((*StartHLSEgressRequest)(nil), "StartHLSEgressRequest")
	proto.RegisterType((*StartHLSEgressResponse)(nil), "StartHLSEgressResponse")
	proto.RegisterType((*StopHLSEgressRequest)(nil), "StopHLSEgressRequest")
	proto.RegisterType((*StopHLSEgressResponse)(nil), "StopHLSEgressResponse")
	proto.RegisterType((*MonitorSwarmsRequest)(nil), "MonitorSwarmsRequest")
	proto.RegisterType((*MonitorSwarmsResponse)(nil), "MonitorSwarmsResponse")
	proto.RegisterType((*BootstrapDHTRequest)(nil), "BootstrapDHTRequest")
	proto.RegisterType((*BootstrapDHTResponse)(nil), "BootstrapDHTResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x86, 0x6f, 0x7b, 0x6f, 0xae, 0xf6, 0x44, 0x2b, 0x94, 0xaf, 0xa2, 0x1b, 0x52, 0x63, 0x42,
	0x5c, 0xa0, 0xd1, 0x8d, 0x0b, 0x37, 0x20, 0xa3, 0x68, 0x4a, 0x62, 0x5a, 0x88, 0x89, 0x1b, 0x32,
	0xca, 0xc4, 0xcc, 0x82, 0xce, 0x38, 0x73, 0xc0, 0xf0, 0xef, 0x4d, 0x87, 0xf2, 0x51, 0x31, 0xc6,
	0x65, 0x9f, 0x37, 0xcf, 0x3b, 0x67, 0x4e, 0x07, 0x1c, 0x2a, 0x79, 0x4b, 0x2a, 0x81, 0x22, 0x38,
	0x83, 0xc2, 0x83, 0xe0, 0x49, 0xfc, 0x41, 0xd5, 0x24, 0x62, 0xef, 0x53, 0xa6, 0xd1, 0x3b, 0x02,
	0x47, 0xa7, 0xdf, 0xa3, 0xa9, 0xe2, 0xbe, 0xd5, 0xb0, 0x9a, 0x4e, 0xb4, 0x6b, 0xc0, 0x50, 0xf1,
	0xa0, 0x04, 0xc5, 0x0d, 0x41, 0x4b, 0x91, 0x68, 0x16, 0x9c, 0x43, 0x31, 0x64, 0x74, 0xc6, 0x7e,
	0x5f, 0x53, 0x06, 0x6f, 0xd3, 0xc8, 0x7a, 0x0e, 0xc1, 0xbf, 0x63, 0x78, 0x9f, 0xbc, 0x29, 0xa6,
	0x75, 0x8c, 0x8a, 0xd1, 0x89, 0xce, 0xea, 0x82, 0x2b, 0xa8, 0x7f, 0x93, 0x2d, 0xc4, 0x9f, 0xcf,
	0xf2, 0xa1, 0x1a, 0x23, 0x55, 0xd8, 0x0b, 0xe3, 0x4c, 0x5f, 0x76, 0xd6, 0xa1, 0xb6, 0x95, 0x64,
	0xa3, 0xd4, 0xa0, 0xb2, 0x8c, 0x48, 0xce, 0xd9, 0x68, 0x23, 0x79, 0xa5, 0x0a, 0xe5, 0x18, 0x85,
	0xdc, 0x32, 0x4c, 0x55, 0x8e, 0xaf, 0x85, 0xbe, 0x48, 0x38, 0x0a, 0x65, 0xd6, 0xb0, 0x12, 0x42,
	0xa8, 0x7c, 0xe1, 0xd9, 0x35, 0x8f, 0xe1, 0x1f, 0xce, 0x25, 0x33, 0x37, 0x74, 0x2f, 0x0e, 0x5a,
	0x26, 0x26, 0x33, 0x96, 0xe0, 0x60, 0x2e, 0x59, 0x64, 0x42, 0xcf, 0x05, 0x9b, 0x8f, 0x7d, 0xdb,
	0x2c, 0xc1, 0xe6, 0xe3, 0xe0, 0x1a, 0x4a, 0x1d, 0x21, 0x50, 0xa3, 0xa2, 0xb2, 0xdb, 0x1b, 0x2c,
	0x7f, 0xcf, 0x09, 0xb8, 0xa8, 0x68, 0xa2, 0xa5, 0x50, 0x98, 0xae, 0x4d, 0xfb, 0x56, 0xe3, 0x6f,
	0xd3, 0x89, 0xf6, 0x57, 0x74, 0xa8, 0xb8, 0x4e, 0x67, 0xcc, 0xdb, 0x8b, 0x51, 0x4e, 0x6f, 0xc1,
	0xcd, 0x9f, 0xee, 0x15, 0x60, 0xef, 0x26, 0x22, 0xed, 0x01, 0x19, 0xc5, 0x4f, 0xed, 0xa8, 0x5f,
	0xf8, 0x93, 0x92, 0xe1, 0x63, 0x77, 0x4d, 0xac, 0x94, 0x74, 0x49, 0x48, 0x56, 0xc4, 0xee, 0x38,
	0xcf, 0x3b, 0x9a, 0xa9, 0x19, 0x7f, 0x65, 0x2f, 0xff, 0xcd, 0x93, 0xbc, 0xfc, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0x4d, 0x65, 0x38, 0x0e, 0x9f, 0x02, 0x00, 0x00,
}
