// Code generated by Wire protocol buffer compiler, do not edit.
// Source: strims.video.v1.HLSEgressCloseStreamResponse in video/v1/hls_egress.proto
package gg.strims.video.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.jvm.JvmField
import okio.ByteString

class HLSEgressCloseStreamResponse(
  unknownFields: ByteString = ByteString.EMPTY
) : Message<HLSEgressCloseStreamResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HLSEgressCloseStreamResponse) return false
    if (unknownFields != other.unknownFields) return false
    return true
  }

  override fun hashCode(): Int = unknownFields.hashCode()

  override fun toString(): String = "HLSEgressCloseStreamResponse{}"

  fun copy(unknownFields: ByteString = this.unknownFields): HLSEgressCloseStreamResponse =
      HLSEgressCloseStreamResponse(unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<HLSEgressCloseStreamResponse> = object :
        ProtoAdapter<HLSEgressCloseStreamResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      HLSEgressCloseStreamResponse::class, 
      "type.googleapis.com/strims.video.v1.HLSEgressCloseStreamResponse", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: HLSEgressCloseStreamResponse): Int {
        var size = value.unknownFields.size
        return size
      }

      override fun encode(writer: ProtoWriter, value: HLSEgressCloseStreamResponse) {
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): HLSEgressCloseStreamResponse {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return HLSEgressCloseStreamResponse(
          unknownFields = unknownFields
        )
      }

      override fun redact(value: HLSEgressCloseStreamResponse): HLSEgressCloseStreamResponse =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
