// Code generated by Wire protocol buffer compiler, do not edit.
// Source: strims.network.v1.Invitation in network/v1/network.proto
package gg.strims.api.network.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class Invitation(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY
  )
  val version: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY
  )
  val data: ByteString = ByteString.EMPTY,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<Invitation, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Invitation) return false
    if (unknownFields != other.unknownFields) return false
    if (version != other.version) return false
    if (data != other.data) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + version.hashCode()
      result = result * 37 + data.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """version=$version"""
    result += """data=$data"""
    return result.joinToString(prefix = "Invitation{", separator = ", ", postfix = "}")
  }

  fun copy(
    version: Int = this.version,
    data: ByteString = this.data,
    unknownFields: ByteString = this.unknownFields
  ): Invitation = Invitation(version, data, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Invitation> = object : ProtoAdapter<Invitation>(
      FieldEncoding.LENGTH_DELIMITED, 
      Invitation::class, 
      "type.googleapis.com/strims.network.v1.Invitation", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: Invitation): Int {
        var size = value.unknownFields.size
        if (value.version != 0) size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.version)
        if (value.data != ByteString.EMPTY) size += ProtoAdapter.BYTES.encodedSizeWithTag(2,
            value.data)
        return size
      }

      override fun encode(writer: ProtoWriter, value: Invitation) {
        if (value.version != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.version)
        if (value.data != ByteString.EMPTY) ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.data)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): Invitation {
        var version: Int = 0
        var data: ByteString = ByteString.EMPTY
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> version = ProtoAdapter.UINT32.decode(reader)
            2 -> data = ProtoAdapter.BYTES.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Invitation(
          version = version,
          data = data,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: Invitation): Invitation = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
