name: simple e2e w/ kind

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/kind-e2e-simple.yaml'
      - 'go.mod'
      - 'go.sum'
      - 'cmd/svc/**'
      - 'pkg/**'
      - 'internal/**'
      - 'test/e2e/**'
  workflow_dispatch:

jobs:
  test:
    name: simple e2e test on kind
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - uses: helm/kind-action@v1.5.0
        with:
          install_only: true
      - run: go install github.com/google/ko@latest
      - run: echo "image=`ko build --local --base-import-paths ./cmd/svc/`" >> $GITHUB_OUTPUT
        id: ko-build
      - run: go test -v ./test/e2e/ -args -strims.image ${{steps.ko-build.outputs.image}}
